# Change these first
owner: foto-andreas # Your GitHub username
repo: Uptime-QL # Your GitHub repository name

# Add your sites here
sites:
  - name: Q-Learning
    url: https://q-learning.de
  - name: Q-Learning Campus
    url: https://q-learning-campus.de

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Uptime-QL
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Q-Learning
  theme: dark
  introTitle: "**Q-Learning** Statusseite"
  introMessage: 
  navbar:
    - title: Status
      href: https://foto-andreas.github.io/Uptime-QL/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
